#!/bin/bash

while getopts ":t:m:v:r:" options; do
  case "${options}" in
    t)
      TAG="${OPTARG}"
    ;;
    m)
      MODE="${OPTARG}"
    ;;
    v)
      VOLUME="${OPTARG}"
    ;;
    r)
      CPU_RATIO="${OPTARG}"
    ;;
  esac
done

if [[ -z "${CPU_RATIO}" ]]; then
  CPU_RATIO=0.5
fi

if [[ -z "${TAG}" ]]; then
  TAG="latest"
fi

TZ=$(cat /etc/timezone &> /dev/null || echo "Europe/Berlin")
PGID=$(id -g `whoami`)
PUID=$(id -u `whoami`)
CPUS=$(getconf _NPROCESSORS_ONLN)
LIMIT=$(echo "${CPUS} * ${CPU_RATIO}" | bc -l)
COLOR_NOTICE='\e[95m'
COLOR_ERROR='\e[91m'
COLOR_NONE='\e[39m'

getLatestRelease() {
  curl --silent "https://api.github.com/repos/$1/releases/latest" | \
    grep '"tag_name":' | \
    sed -E 's/.*"([^"]+)".*/\1/'
}

logDefault()
{
  echo -e "$1"
}

logNotice()
{
  echo -e "${COLOR_NOTICE}$1${COLOR_NONE}"
}

logError()
{
  echo -e "${COLOR_ERROR}$1${COLOR_NONE}" 1>&2
}

build()
{
  logNotice "Getting latest release of \"multiarch/qemu-user-static\""

  LATEST=$(getLatestRelease multiarch/qemu-user-static)

  logDefault "> Latest release of \"multiarch/qemu-user-static\" is ${LATEST}"

  logNotice "Fetching \"multiarch/qemu-user-static\""

  for ARCH in aarch64 arm x86_64; do
    curl -sL https://github.com/multiarch/qemu-user-static/releases/download/v4.0.0-2/x86_64_qemu-${ARCH}-static.tar.gz | tar -C ./root -xf -

    logDefault "> fetched ${ARCH}"
  done

  logNotice "Creating Dockerfiles"

  for DOCKER_ARCH in amd64 arm32v7 arm64v8; do
    case ${DOCKER_ARCH} in
      amd64)
        QEMU_ARCH="x86_64"
        ;;
      arm32v7)
        QEMU_ARCH="arm"
        ;;
      arm64v8)
        QEMU_ARCH="aarch64"
        ;;
    esac

    cp Dockerfile.multi Dockerfile.${DOCKER_ARCH}

    sed -i "" "s|__BASE_ARCH__|${DOCKER_ARCH}|g" Dockerfile.${DOCKER_ARCH}
    sed -i "" "s|__QEMU_ARCH__|${QEMU_ARCH}|g" Dockerfile.${DOCKER_ARCH}

    if [[ ${DOCKER_ARCH} == 'amd64' ]]; then
      sed -i "" "/__CROSS_/d" Dockerfile.${DOCKER_ARCH}
    else
      sed -i "" "s/__CROSS_//g" Dockerfile.${DOCKER_ARCH}
    fi

    logDefault "> created Dockerfile.${DOCKER_ARCH}"
  done

  logNotice "Building images"

  for DOCKER_ARCH in amd64 arm32v7 arm64v8; do
    docker build --compress --no-cache --force-rm --squash -t qoopido/easyepg.minimal:${TAG}-${DOCKER_ARCH} -f Dockerfile.${DOCKER_ARCH} .

    logDefault "> built qoopido/easyepg.minimal:${TAG}-${DOCKER_ARCH}"
  done
}

publish() {
  logNotice "Publishing images"

  for DOCKER_ARCH in amd64 arm32v7 arm64v8; do
    docker push qoopido/easyepg.minimal:${TAG}-${DOCKER_ARCH}

    logDefault "> pushed qoopido/easyepg.minimal:${TAG}-${DOCKER_ARCH}"
  done

  logNotice "Processing manifest"

  docker manifest create qoopido/easyepg.minimal:${TAG} qoopido/easyepg.minimal:${TAG}-amd64 qoopido/easyepg.minimal:${TAG}-arm32v7 qoopido/easyepg.minimal:${TAG}-arm64v8

  logDefault "> created manifest"

  docker manifest annotate qoopido/easyepg.minimal:${TAG} qoopido/easyepg.minimal:${TAG}-arm32v7 --os linux --arch arm
  docker manifest annotate qoopido/easyepg.minimal:${TAG} qoopido/easyepg.minimal:${TAG}-arm64v8 --os linux --arch arm64 --variant armv8

  logDefault "> added annotations"

  docker manifest push qoopido/easyepg.minimal:${TAG} --purge

  logDefault "> pushed manifest"
}

create()
{
  if [[ -z "${VOLUME}" || ! -d "${VOLUME}" || ! -w "${VOLUME}" ]]; then
    logError "Usage: eemd -m create -v [path to volume]"
    exit 1
  fi

  VOLUME=$(cd ${VOLUME} && pwd -P)

  docker create --name=easyepg.admin --tmpfs /tmp --tmpfs /var/log --cpus ${LIMIT} -e MODE=admin -e PUID=${PUID} -e PGID=${PGID} -e TZ=${TZ} -v ${VOLUME}:/easyepg qoopido/easyepg.minimal:${TAG}
  docker create --name=easyepg.run --tmpfs /tmp --tmpfs /var/log --cpus ${LIMIT} -e MODE=run -e PUID=${PUID} -e PGID=${PGID} -e TZ=${TZ} -v ${VOLUME}:/easyepg qoopido/easyepg.minimal:${TAG}
  docker create --name=easyepg.cron --restart unless-stopped --tmpfs /tmp --tmpfs /var/log --cpus ${LIMIT} -e MODE=cron -e PUID=${PUID} -e PGID=${PGID} -e TZ=${TZ} -v ${VOLUME}:/easyepg qoopido/easyepg.minimal:${TAG}
}

case "${MODE}" in
  build)
    build
    ;;
  publish)
    publish
    ;;
  create)
    create
    ;;
  *)
    logError "Usage: eemd -m [build|publish|create]"
    logError "       -t: tag for the image"
    logError "           => used by [build|publish|create], defaults to \"latest\""
    logError "       -v: string containing the path to the volume for the container to use"
    logError "           => required for [create]"
    logError "       -r: float for the CPU ratio of the container"
    logError "           => used by [create], defaults to 0.5"
    exit 1
    ;;
esac

exit 0
