#!/bin/bash

while getopts ":m:v:r:" options; do
  case "${options}" in
    m)
      MODE="${OPTARG}"
    ;;
    v)
      VOLUME="${OPTARG}"
    ;;
    r)
      CPU_RATIO="${OPTARG}"
    ;;
  esac
done

if [[ -z "${CPU_RATIO}" ]]; then
  CPU_RATIO=0.5
fi

TZ=$(cat /etc/timezone)
PGID=$(id -g `whoami`)
PUID=$(id -u `whoami`)
CPUS=$(grep -c ^processor /proc/cpuinfo)
LIMIT=$(echo "${CPUS} * ${CPU_RATIO}" | bc -l)
COLOR_NOTICE='\e[95m'
COLOR_ERROR='\e[91m'
COLOR_NONE='\e[39m'

logDefault()
{
  echo -e "$1"
}

logNotice()
{
  echo -e "${COLOR_NOTICE}$1${COLOR_NONE}"
}

logError()
{
  echo -e "${COLOR_ERROR}$1${COLOR_NONE}" 1>&2
}

build()
{
  docker build --compress --no-cache --force-rm -t qoopido/easyepg.minimal:1.0.6-rc.3 .
}

admin()
{
  if [[ -z "${VOLUME}" || ! -d "${VOLUME}" || ! -w "${VOLUME}" ]]; then
    logError "Usage: eemd -m admin -v [path to volume]"
    exit 1
  fi

  VOLUME=$(cd ${VOLUME} && pwd -P)

  docker run --cpus ${LIMIT} --rm -ti -d -e "MODE=admin" -e "TZ=${TZ}" -e "PGID=${PGID}" -e "PUID=${PUID}" -v ${VOLUME}:/easyepg --name easyepg-admin qoopido/easyepg.minimal:1.0.6-rc.3
  docker exec -ti easyepg-admin /bin/bash
  docker stop easyepg-admin
}

run()
{
  if [[ -z "${VOLUME}" || ! -d "${VOLUME}" || ! -w "${VOLUME}" ]]; then
    logError "Usage: eemd -m run -v \"[path to volume]\""
    exit 1
  fi

  VOLUME=$(cd ${VOLUME} && pwd -P)

  docker run --cpus ${LIMIT} --rm -e "MODE=run" -e "TZ=${TZ}" -e "PGID=${PGID}" -e "PUID=${PUID}" -v ${VOLUME}:/easyepg --name easyepg-run qoopido/easyepg.minimal:1.0.6-rc.3
}

cron()
{
  if [[ -z "${VOLUME}" || ! -d "${VOLUME}" || ! -w "${VOLUME}" ]]; then
    logError "Usage: eemd -m cron -v \"[path to volume]\""
    exit 1
  fi

  VOLUME=$(cd ${VOLUME} && pwd -P)

  docker run --rm --cpus ${LIMIT} -ti -d -e "MODE=cron" -e "TZ=${TZ}" -e "PGID=${PGID}" -e "PUID=${PUID}" -v ${VOLUME}:/easyepg --name easyepg-cron qoopido/easyepg.minimal:1.0.6-rc.3
}

case "${MODE}" in
  build)
    build
    ;;
  admin)
    admin
    ;;
  run)
    run
    ;;
  cron)
    cron
    ;;
  *)
    logError "Usage: eemd -m [build|admin|run|cron]"
    logError "       -v: string containing the path to the volume for the container to use"
    logError "           => required for \"run\" and \"cron\""
    logError "       -r: float for the CPU ratio of the container"
    logError "           => used by \"admin\", \"run\" and \"cron\", defaults to 0.5"
    exit 1
    ;;
esac

exit 0
