#!/bin/bash

TZ=$(cat /etc/timezone)
PGID=$(id -g `whoami`)
PUID=$(id -u `whoami`)
COLOR_NOTICE='\e[95m'
COLOR_ERROR='\e[91m'
COLOR_NONE='\e[39m'

logDefault()
{
  echo -e "$1"
}

logNotice()
{
  echo -e "${COLOR_NOTICE}$1${COLOR_NONE}"
}

logError()
{
  echo -e "${COLOR_ERROR}$1${COLOR_NONE}" 1>&2
}

build()
{
  docker build --compress --no-cache --force-rm -t qoopido/easyepg.minimal:1.0.6-rc.2 .
}

admin()
{
  if [[ ! -d ${1} || ! -w ${1} ]]; then
    logError "Usage: eemd admin [path to volume]"
    exit 1
  fi

  VOLUME=$(cd ${1} && pwd -P)

  docker run --cpus 2.0 --rm -ti -d -e "MODE=admin" -e "TZ=${TZ}" -e "PGID=${PGID}" -e "PUID=${PUID}" -v ${VOLUME}:/easyepg --name easyepg-admin qoopido/easyepg.minimal:1.0.6-rc.2
  docker exec -ti easyepg-admin /bin/bash
  docker stop easyepg-admin
}

run()
{
  if [[ ! -d ${1} || ! -w ${1} ]]; then
    logError "Usage: eemd run [path to volume]"
    exit 1
  fi

  VOLUME=$(cd ${1} && pwd -P)

  docker run --cpus 2.0 --rm -e "MODE=run" -e "TZ=${TZ}" -e "PGID=${PGID}" -e "PUID=${PUID}" -v ${VOLUME}:/easyepg --name easyepg-run qoopido/easyepg.minimal:1.0.6-rc.2
}

cron()
{
  if [[ ! -d ${1} || ! -w ${1} ]]; then
    logError "Usage: eemd cron [path to volume]"
    exit 1
  fi

  VOLUME=$(cd ${1} && pwd -P)

  docker run --rm --cpus 2.0 -ti -d -e "MODE=cron" -e "TZ=${TZ}" -e "PGID=${PGID}" -e "PUID=${PUID}" -v ${VOLUME}:/easyepg --name easyepg-cron qoopido/easyepg.minimal:1.0.6-rc.2
}

case "${1}" in
  build)
    build
    ;;
  admin)
    admin ${2}
    ;;
  run)
    run ${2}
    ;;
  cron)
    cron ${2}
    ;;
  *)
    logError "Usage: eemd [build|admin|run|cron]"
    exit 1
    ;;
esac

exit 0
