#!/bin/bash
set -e
set -f

echo "easyepg:x:${GID}:" > /etc/group
echo "easyepg:x:${UID}:${GID}:easyepg:/:/bin/false" > /etc/passwd
echo "easyepg:!::0:::::" > /etc/shadow

# su -s /bin/bash -c "TERM=xterm /usr/local/bin/easyepg.process" ${USERNAME}
/easyepg
