name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Preparation
      run: |
        QEMU_VERSION = $(curl --silent "https://api.github.com/repos/multiarch/qemu-user-static/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo ${QEMU_VERSION}
    # - name: Build the Docker image
    # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
