name: Docker Image CI
on: [push]
jobs:
  arm32v7:
    runs-on: ubuntu-18.04
    env:
      TAG: latest
    steps:
      - uses: actions/checkout@v1
        id: arm32v7
      - name: Preparation
        run: |
          # update packages & install requirements
          sudo apt-get -qy update
          sudo apt-get -qy --no-install-recommends install qemu-user-static binfmt-support moreutils
          # copy qemu for use via Dockerfile
          cp /usr/bin/qemu-arm-static ./root
          cp /usr/bin/qemu-aarch64-static ./root
          # enable Dockers expermiental features for squash/manifest support
          export DOCKER_CONFIG=${HOME}/.docker/
          sudo service docker restart
      - name: Build amd64
        run: |
          docker build --compress --no-cache --force-rm --squash -t qoopido/easyepg.minimal:${TAG}-amd64 -f Dockerfile.amd64 .
      - name: Build arm32v7
        run: |
          docker build --compress --no-cache --force-rm --squash -t qoopido/easyepg.minimal:${TAG}-arm32v7 -f Dockerfile.arm32v7 .
      - name: Build arm64v8
        run: |
          docker build --compress --no-cache --force-rm --squash -t qoopido/easyepg.minimal:${TAG}-arm64v8 -f Dockerfile.arm64v8 .
      - name: Create manifest
        run: |
          docker manifest create qoopido/easyepg.minimal:${TAG} qoopido/easyepg.minimal:${TAG}-amd64 qoopido/easyepg.minimal:${TAG}-arm32v7 qoopido/easyepg.minimal:${TAG}-arm64v8
          docker manifest annotate qoopido/easyepg.minimal:${TAG} qoopido/easyepg.minimal:${TAG}-arm32v7 --os linux --arch arm
          docker manifest annotate qoopido/easyepg.minimal:${TAG} qoopido/easyepg.minimal:${TAG}-arm64v8 --os linux --arch arm64 --variant armv8
          # docker manifest push qoopido/easyepg.minimal:${TAG} --purge
