name: Docker Image CI
on: [push]
jobs:
#  amd64:
#    runs-on: ubuntu-18.04
#    env:
#      TAG: latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Build amd64
#      run: docker build --compress --no-cache --force-rm -t qoopido/easyepg.minimal:amd64-${TAG} -f Dockerfile.amd64 .
  arm32v7:
    runs-on: ubuntu-18.04
    env:
      TAG: latest
    steps:
      - uses: actions/checkout@v1
        id: arm32v7
      - name: Preparation
        run: |
          sudo apt-get -qy update
          sudo apt-get -qy --no-install-recommends install qemu-user-static binfmt-support moreutils
          cp /usr/bin/qemu-arm-static ./root
          cp /usr/bin/qemu-aarch64-static ./root
          sudo echo "$(cat /etc/docker/daemon.json) {\"experimental\": true}" | jq -s add | sponge /etc/docker/daemon.json
          sudo service docker restart
      #- name: Build amd64
      #  run: |
      #    docker build --compress --no-cache --force-rm -t qoopido/easyepg.minimal:${TAG}-amd64 -f Dockerfile.amd64 .
      - name: Build arm32v7
        run: |
          docker build --compress --no-cache --force-rm --squash -t qoopido/easyepg.minimal:${TAG}-arm32v7 -f Dockerfile.arm32v7 .
      #- name: Build arm64v8
      #  run: |
      #    docker build --compress --no-cache --force-rm -t qoopido/easyepg.minimal:${TAG}-arm64v8 -f Dockerfile.arm64v8 .
#  arm64v8:
#    runs-on: ubuntu-18.04
#    env:
#      TAG: latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: uraimo/run-on-arch-action@v1.0.6
#        id: arm64v8
#        with:
#          architecture: aarch64
#          distribution: ubuntu18.04
#          run: |
#            echo ::set-output name=id::$(docker build --compress --no-cache --force-rm -t qoopido/easyepg.minimal:arm64v8-${TAG} -f Dockerfile.amd64 .)
#      - name: Build arm64v8
#        run: |
#          echo "Container ID is ${{ steps.arm32v7.outputs.id }}"
