name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: latest
      QEMU_VERSION: 4.1.1-1
    steps:
    - uses: actions/checkout@v1
    - name: Preparation
      run: |
        curl -sL -o ./root/qemu-x86_64-static https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/x86_64_qemu-x86_64-static
        curl -sL -o ./root/qemu-arm-static https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/x86_64_qemu-arm-static
        curl -sL -o ./root/qemu-aarch64-static https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/x86_64_qemu-aarch64-static
    - name: Build amd64
      run: docker build --compress --no-cache --force-rm -t qoopido/easyepg.minimal:amd64-${TAG} -f Dockerfile.amd64 .
    #- name: Build arm32v7
    #  run: docker build --compress --no-cache --force-rm -t qoopido/easyepg.minimal:arm32v7-${TAG} -f Dockerfile.arm32v7 .
    #- name: Build arm64v8
    #  run: docker build --compress --no-cache --force-rm -t qoopido/easyepg.minimal:arm64v8-${TAG} -f Dockerfile.arm64v8 .
    # - name: Build the Docker image
    # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
