name: Lite-Scratch
on:
  workflow_dispatch:
#  push:
#    branches:
#    - lite-scratch
#  schedule:
#  - cron: '0 0 * * *'
env:
  DEBIAN_FRONTEND: noninteractive
  TEMPORARY_DIRECTORY: /home/runner/work/_temp
jobs:
  build:
    name: Build multiarch images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: lite-scratch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Authenticate registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build image
        run: |
          DOCKER_TAG="lite-scratch-${GITHUB_SHA}-$(date +'%Y%m%d-%H%M%S')"
          
          # docker buildx create --name builder --driver docker-container --bootstrap
          # docker buildx use builder
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --compress --no-cache --force-rm --push -t qoopido/easyepg.minimal:${DOCKER_TAG} -t qoopido/easyepg.minimal:lite-scratch .
